### PR TITLE
switch to yarn

### LINKED ISSUE #385: package-lock.json changes from npm install
On a fresh `master` checkout, running `npm install` causes this change to `package-lock.json`:

```diff
diff --git a/package-lock.json b/package-lock.json
index 23ef919..6eb9a7a 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -8252,6 +8252,7 @@
                 "find-node-modules": "2.0.0",
                 "find-root": "1.1.0",
                 "fs-extra": "8.1.0",
+                "glob": "7.1.4",
                 "inquirer": "6.5.0",
                 "is-utf8": "^0.2.1",
                 "lodash": "4.17.15",
@@ -8331,6 +8332,20 @@
                         "tmp": "^0.0.33"
                     }
                 },
+                "glob": {
+                    "version": "7.1.4",
+                    "resolved": "https://registry.npmjs.org/glob/-/glob-7.1.4.tgz",
+                    "integrity": "sha512-hkLPepehmnKk41pUGm3sYxoFs/umurYfYJCerbXEyFIWcAzvpipAgVkBqqT9RBKMGjnq6kMuyYwha6csxbiM1A==",
+                    "dev": true,
+                    "requires": {
+                        "fs.realpath": "^1.0.0",
+                        "inflight": "^1.0.4",
+                        "inherits": "2",
+                        "minimatch": "^3.0.4",
+                        "once": "^1.3.0",
+                        "path-is-absolute": "^1.0.0"
+                    }
+                },
                 "iconv-lite": {
                     "version": "0.4.24",
                     "resolved": "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz",
@@ -19087,8 +19102,7 @@
                     "version": "3.1.0",
                     "resolved": "https://registry.npmjs.org/callsites/-/callsites-3.1.0.tgz",
                     "integrity": "sha512-P8BjAsXvZS+VIDUI11hHCQEv74YT67YUi5JJFNWIqL235sBmjX4+qx9Muvls5ivyNENctx46xQLQ3aTuE7ssaQ==",
-                    "dev": true,
-                    "optional": true
+                    "dev": true
                 }
             }
         },

```

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #385

### CODE REVIEW

**Comment by peterbe** [comment]
Is `jest` supposed to work? I.e. `yarn test` is failing but I don't know if that's because of this or because it's always broken and hasn't been part of CI.

**Comment by peterbe** [comment]
@schalkneethling Are you still interested in this?

By the way, I learned something amazing recently. 
Suppose that your in a branch in a project that uses yarn. Your branch has edits to `package.json` and `yarn.lock` and if you now do a `git merge master` into your branch you're confronted with a merge conflict and a big fat diff to that monster of a file `yarn.lock`. (By the way, I think `yarn.lock` files are generally smaller in size than `package-lock.json` files) Instead of manually have to resolve the diff or to blow it away and starting over; you can just type `yarn install` and yarn will notice the merge conflict and resolve it intelligently based on the contents of `package.json`.

**Comment by schalkneethling** [comment]
> Are you still interested in this?

Most definitely.

> Instead of manually have to resolve the diff or to blow it away and starting over; you can just type `yarn install` and yarn will notice the merge conflict and resolve it intelligently based on the contents of `package.json`.

That is super neat.

**Pull request merged**
