### PR TITLE
Displays clippy button only when hovering .example-choice elements in demo

### LINKED ISSUE #582: Clipboard in code examples should appear on hover only
Could we change how the clipboard extension works for the code examples? Right now, the clipboard is always visible on the focused code example. 

clipboard

If I want to copy an example that isn't focused, I would go to highlight the text, which also switches the focus in the example on mouse up. I think it would make more sense if the clipboard is only visible when hovering over an example so when users are going to select something to copy it, they'd see the clipboard instead. It also would cut down on the visual noise in the examples if the clipboard is only shown when the user would need it.

cc: @tannerdolby

### PR DESCRIPTION
**Pull request by tannerdolby**
Fixes #582

### CODE REVIEW

**Comment by tannerdolby** [comment]
I'm not entirely sure the mouseover/mouseout events need to be added to change the `aria-hidden` value when example choices are hovered. Still trying to convince myself its necessary to hide/show the clippy btns from assistive technology on hover. The clippy button isn't really a "tooltip" in my eyes as its more than just plain text, its a clickable `<button>` which triggers some action, that being the copy-to-clipboard utility. I'm pretending our clippy btn is a tooltip when referring to the info from this a11y site [Tooltip widgets](https://www.accessibility-developer-guide.com/examples/widgets/tooltips/)

> Some tooltips appear automatically on hovering and/or focusing the described element. Their contents are announced immediately by screen readers; as such, screen reader users usually do not even have to know about the existence of such a tooltip.

To prevent redundant announcements in screen readers, we hide the clippy button from them using `aria-hidden`. I think this justifies the fact that having `aria-hidden` around to reduce redundant announcements is ideal, but does it need to be changed on hover? or can this PR only consist of the CSS changes and leave the aria-hidden values at their initial ones, which would be `aria-hidden="true"` if the example choice isn't selected and `aria-hidden="false"` when choices are selected.

CC @schalkneethling @peterbe

**Comment by schalkneethling** [comment]
Thank you for jumping on this @tannerdolby. I am going to let this one simmer for a bit while we work on the redesign. One concern I have is that, while the interactive examples are generally not great on mobile at the moment, this will essentially remove the ability to use the copy to clipboard function on mobile/small-viewports.

A very valid argument would be, "Well, how many people even use it on mobile?" 😄 

I do think we need to talk about it a little more and also ensure we keep the interaction the same across all forms of code examples. Thank you again for all of your valuable contributions.

**Comment by tannerdolby** [comment]
Your welcome @schalkneethling. Ok that works for me, I agree this should be apart of the bigger redesign for interactive examples on mobile/small viewports and have some more discussion around it. 

> One concern I have is that, while the interactive examples are generally not great on mobile at the moment, this will essentially remove the ability to use the copy to clipboard function on mobile/small-viewports. A very valid argument would be, "Well, how many people even use it on mobile?" 😄

This was in the back of my mind will having a look at the flex example http://127.0.0.1:9090/pages/css/flex.html locally on my mobile phone. Food for thought, what if we kept the interactivity on hover for viewports above tablets (768px and up, ie any screen that doesn't rely on touch) like @dalexsy mentioned in #582, then we detect the viewport width either using a media query or programmatically with js at this "cutoff" width and apply styles/classes to bring the clippy icon back to its initial design where it stays locked in the right corner if an `.example-choice` is targeted. 

This way the mobile/small viewport screens below 768px can still use the clippy functionality (which granted might not be used often on mobile) but atleast would provide the ability to copy-to-clipboard if someone were quickly referencing an MDN docs page on their mobile phone to include a code snippet in an email/text message/ etc. I do agree we should keep interaction the same across code examples, i'm excited to continue this discussion. I think there is already a interactive example redesign discussion created in Yari so I will try finding that and drop the link here.

**Comment by tannerdolby** [comment]
Food for thought, what if we kept the interactivity on hover for viewports above tablets (768px and up, ie any screen that doesn't rely on touch) like @dalexsy mentioned in #582, then we detect the viewport width either using a media query or programmatically with js at this "cutoff" width and apply styles/classes to bring the clippy icon back to its initial design where it stays locked in the right corner if an `.example-choice` is targeted and remove the mouseover/mouseout event listeners. 

This way the mobile/small viewport screens below 768px can still use the clippy functionality (which granted might not be used often on mobile) but atleast would provide the ability to copy-to-clipboard if someone were quickly referencing an MDN docs page on their mobile phone to include a code snippet in an email/text message/ etc. I do agree we should keep interaction the same across code examples, i'm excited to continue this discussion. I think there is already a interactive example redesign discussion created in Yari so I will try finding that and drop the link here.

**Review by schalkneethling — APPROVED** [review]
r+

**Pull request merged**
