### PR TITLE
ci(npm-published-simulation): verify that expected files exist after build

### PR DESCRIPTION
**Pull request by caugner**

### CODE REVIEW

**Comment by caugner** [comment]
@NiedziolkaMichal Once this is merged, in https://github.com/mdn/bob/pull/1119 you could add paths to wat examples that you expect to have been built.

**Comment by NiedziolkaMichal** [comment]
@caugner ok

**Comment by caugner** [comment]
> @caugner ok

Actually, we can just add a wat path in this PR, see: ac8a4f2e88a099fc8ab644dd44f1da55ce0a8c5a

Now, this should fail until #1119 is merged. 😇 

**edit**: And it does, as expected: https://github.com/mdn/bob/actions/runs/4264754261/jobs/7423238712#step:9:46

**Comment by NiedziolkaMichal** [comment]
@caugner Those are all expected WAT files
```
test -e pages/wat/abs.html
test -e pages/wat/add.html
test -e pages/wat/and.html
test -e pages/wat/block.html
test -e pages/wat/br.html
test -e pages/wat/call.html
test -e pages/wat/ceil.html
test -e pages/wat/clz.html
test -e pages/wat/const.html
test -e pages/wat/convert.html
test -e pages/wat/copysign.html
test -e pages/wat/ctz.html
test -e pages/wat/demote.html
test -e pages/wat/div.html
test -e pages/wat/drop.html
test -e pages/wat/end.html
test -e pages/wat/eq.html
test -e pages/wat/extend.html
test -e pages/wat/floor.html
test -e pages/wat/ge.html
test -e pages/wat/global.html
test -e pages/wat/global_get.html
test -e pages/wat/global_set.html
test -e pages/wat/grow.html
test -e pages/wat/gt.html
test -e pages/wat/if...else.html
test -e pages/wat/le.html
test -e pages/wat/load.html
test -e pages/wat/local.html
test -e pages/wat/local_tee.html
test -e pages/wat/loop.html
test -e pages/wat/lt.html
test -e pages/wat/max.html
test -e pages/wat/min.html
test -e pages/wat/mul.html
test -e pages/wat/ne.html
test -e pages/wat/nearest.html
test -e pages/wat/neg.html
test -e pages/wat/nop.html
test -e pages/wat/or.html
test -e pages/wat/popcnt.html
test -e pages/wat/promote.html
test -e pages/wat/reinterpret.html
test -e pages/wat/rem.html
test -e pages/wat/return.html
test -e pages/wat/rotl.html
test -e pages/wat/rotr.html
test -e pages/wat/select.html
test -e pages/wat/shl.html
test -e pages/wat/shr.html
test -e pages/wat/size.html
test -e pages/wat/sqrt.html
test -e pages/wat/store.html
test -e pages/wat/sub.html
test -e pages/wat/trunc_float_to_float.html
test -e pages/wat/trunc_float_to_int.html
test -e pages/wat/unreachable.html
test -e pages/wat/wrap.html
test -e pages/wat/xor.html
```

**Comment by caugner** [comment]
We don't need to list all examples, I think one per type should suffice.

**Comment by caugner** [comment]
And one more 🍿

**Comment by caugner** [comment]
@NiedziolkaMichal If you could have a look at the changes and approve it (it's not the most elegant way of testing the build, but it's pragmatic and should catch any change that prevents one of those files from being built/copied), we can get bob v3.0.2 out there. 😃

**Review by NiedziolkaMichal — APPROVED** [review]

**Comment by NiedziolkaMichal** [comment]
It looks good. In a few minutes, I will also create another PR fixing minor regression.

**Pull request merged**
