### PR TITLE
enable exceptions flag for wasm

### LINKED ISSUE #781: Enable WebAssemblyExceptions
FF100 adds support for [WebAssembly Exception handling](https://github.com/mdn/content/issues/14392). However if you try run any exception handling code in the interactive examples this fails (even if the browser supports it):

image

That's almost certainly because the [web assembly binary toolkit](https://github.com/webassembly/wabt) is being used to convert the .wat file to wasm, and that has not had the enable-exceptions flag set. 

Can we enable it. Testing this is all too hard at the best of times :-(

### PR DESCRIPTION
**Pull request by fiji-flo**
Fixes #781.

### CODE REVIEW

**Comment by fiji-flo** [comment]
This should fix: https://github.com/mdn/interactive-examples/issues/2106

I haven't run this locally yet. Maybe someone beats me to it.

**Comment by fiji-flo** [comment]
@schalkneethling this works. Could you see that Hamish can use it?

**Comment by schalkneethling** [comment]
This LGTM, thanks @fiji-flo - @hamishwillee is this what you needed? Thanks!

**Comment by hamishwillee** [comment]
@schalkneethling Probably - certainly its a supported feature: https://github.com/WebAssembly/wabt/blob/main/src/wabt.post.js#L19
But the only way to know for sure would be to write an example that uses exceptions. I don't plan on doing that for a little while (its on the queue). I don't think it would do any harm to merge this though.

**Comment by hamishwillee** [comment]
PS Thanks @fiji-flo !

**Comment by schalkneethling** [comment]
Thank you, @hamishwillee and @fiji-flo! Merging.

**Pull request merged**
