### PR TITLE
Use Webpack to bundle CSS

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates the code to use Webpack to bundle the CSS files for editor bundles that have been converted to use Webpack.

### CODE REVIEW

**Review by caugner — APPROVED** [review]
LGTM, but I noticed that the CSS was no longer minimized, so I pushed a commit that adds the `CssMinimizerPlugin`.

@queengooborg Please merge if it looks good to you.

**Comment by queengooborg** [comment]
Thanks for adding that!  I had auto-merge turned on so this would get merged right away once approved, though in hindsight I probably shouldn't have toggled it on... ;P

**Comment by caugner** [comment]
That's so weird that it merged despite the checks **not** passing. 🤷

**Comment by queengooborg** [comment]
> That's so weird that it merged despite the checks **not** passing. 🤷

The main test isn't actually required on this repository...for some odd reason.

**Pull request merged**
