### PR TITLE
Tabbed examples use IFrame instead of Shadow DOM

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
This PR makes tabbed interactive examples, used in HTML elements and recently in some CSS properties, display its output in nested iframe instead of in shadow DOM. Reason of this change, is to enable usage of CSS at-rules and WebAPI methods suggested by @wbamberg , which often are not compatible with shadow DOM. For example it should fix PR [#2089](https://github.com/mdn/interactive-examples/pull/2089) on firefox and allow [document.querySelector()](https://interactive-examples.mdn.mozilla.net/pages/webapi-tabbed/document-queryselector.html) example to use "document" instead of "getShadowRoot()".

This change doesn't offer any worse experience, but there are some very minor differences. Currently when example is too wide, horizontal scrollbar is not shown, while vertical scroll bar is shown even when it is not needed:
**Previous:**
image
**Current:**
image

**Previous:**
image
**Current:**
image

I have checked plenty of published examples and they are working fine with new method. URL fragments and links opened in new tabs, are working well too. WebAPI console works well, as it can be seen in this picture:
image

@caugner Could you review it please?

### CODE REVIEW

**Review by queengooborg — APPROVED** [review]
This looks good to me -- after talking with Will at TPAC about this, it sounds like this will open the doors for many more interactive examples!

**Comment by NiedziolkaMichal** [comment]
@queengooborg Thanks for the review. I have already made few interactive examples that are dependent on this PR, so it would be great to finally have it working.

**Comment by queengooborg** [comment]
Could you resolve the merge conflicts so we can get this going?

**Comment by NiedziolkaMichal** [comment]
@queengooborg It's done

**Comment by queengooborg** [comment]
Yikes, something weird happened with the merge commit and now it's saying a lot of changes are being made that shouldn't be... :/

**Pull request closed without merging**
