### PR TITLE
Update CodeMirror to v6 & drop Browserify

### LINKED ISSUE #851: Migrate to CodeMirror v6
## Background

So far, we have been bundling CodeMirror v5 ourselves by concatenating and minifiying several CodeMirror source files:

https://github.com/mdn/bob/blob/1669f37ca65db82afad00fcd8112c454d96d3068/lib/bundler.js#L70-L86

We have been building to bundles:

1. `codeMirror` (a.k.a. `codemirror-5-50-2`):
  https://github.com/mdn/bob/blob/1669f37ca65db82afad00fcd8112c454d96d3068/bundles.json#L4-L13
2. `codeMirrorTabbed` (a.k.a. `codemirror-tabbed-5-50-2`)
  https://github.com/mdn/bob/blob/1669f37ca65db82afad00fcd8112c454d96d3068/bundles.json#L17-L28

## Problem

In CodeMirror v6, this is no longer possible as `node_modules/codemirror` and `node_modules/@codemirror/*` no longer contain sources, but only a `dist/` folder with a single ESM (`index.js`) and CommonJS (`index.cjs`) entrypoint.

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
This PR upgrades CodeMirror to version 6, which seems to be written from scratch. New appearance is pretty much the same, except for some minor differences:

- Web Assembly looks exactly the same
- HTML looks exactly the same, except for hex entities:
**OLD:**
image
**NEW:**
image
- CSS has few differences. @layer shouldn't be highlighted(I posted PR in CodeMirror repo about this already). Dot inside Class Selector is not highlighted, but it would require replacing parser. Now also more functions & keywords are colored, so it's a good change. Keyword "all" in @media shouldn't be blue, but it shares color with "from", "selector" & other things which should be blue. 50% in @keyframes should also have color, but it's not tagged.
**OLD**
image
**NEW:**
image
- JavaScript has most changes and unfortunately many of them are for the worse. Values undefined, NaN, Infinity, "arguments" share color with variable names. References to already existing variables share color as variable names. ${} share color with normal parethesis. I will file an issue about them in CodeMirror.
**OLD:**
image
**NEW:**
image

Pretty much all of those changes would require rewritting parser and then maintaining it on BOB repo. Instead I will create PRs in Code Mirror and maybe they will be accepted.

browserify & esmify dependencies are dropped. Please take a look if this code should be removed from webpack.config:
```js
  resolve: {
    fallback: {
      fs: false,
      path: require.resolve("path-browserify"),
    },
  }
```

I have made whole CodeMirror code be in codemirror.js & codemirror.css.
When #888 is merged, I can make CodeMirror support for it too.

Fixes #851
I am also pretty sure that this PR will fix issue with gutters sometimes collapsing.

### CODE REVIEW

**Comment by queengooborg** [comment]
In regards to the `resolve: {}` configuration, those were added because of the `wabt` dependency, so they cannot be removed.

Thanks for taking the initiative on this, this is looking amazing to me!

**Comment by queengooborg** [comment]
A little nit: could we replace `code-mirror` with `codemirror`?  This retains consistency with the existing filenames, and the package name is one word rather than two!

**Comment by NiedziolkaMichal** [comment]
That's a good idea. It's done.

**Review by queengooborg — APPROVED** [review]
Thank you, this is all LGTM!  🎉

**Pull request merged**
