### PR TITLE
feat: Added wasm example type

### LINKED ISSUE #606: Adding wasm interactive examples
I recently added docs for wasm control flow operators, and I hope to continue adding additional reference docs for other parts of wasm like memory and numerical operations.

I added examples to all pages, but those examples are not interactive. So here's my question, would you folks be open to me adding a new interactive example type for wasm? I think it would be most useful as tabbed where one tab is for the wasm and another one is for js, since wasm is basically useless without js.

I've already done the basic work for this, but before I'm putting in more work I'd like to make sure you folks are on board.

CC @schalkneethling, I was told that you're the one that I should talk to about this.

### PR DESCRIPTION
**Pull request by MendyBerger**
Resolves #606 

Since this is a larger PR I feel the need to explain some of the decisions I made.

I first planned on adding a new tab to the `tabbed-webapi` example type. I was able to get a working example, but it had the following issues:
1) The `tabbed-webapi` example type isn't really used anywhere yet, so I wasn't sure that `tabbed-webapi` is here to stay.
2) The console in the `tabbed-webapi` example is not as good as the JavaScript examples console.
3) The `tabbed-webapi` examples run on page load, but I think that for wasm it would make more sense to behave like the JS examples that have a run button.

Because of the aforementioned reasons I decided to take a different route, I cloned the JS example with all its files and used it as a base for a new `wat` example type, I also had to bring in some functionality from the tabbed examples to enable the WAT and JavaScript tabs.
This new wat example type has some code that is duplicated from the JavaScript example type, especially in the css where they're almost if not completely the same, but I opted for a separate file so that one can be changed without considering the other.

The way meta.json file for a wat example would look like this:
```JSON
{
    "pages": {
        "???": {
            "watExampleCode": "./live-examples/wat-examples/???.wat",
            "jsExampleCode": "./live-examples/wat-examples/???.js",
            "fileName": "???.html",
            "title": "???",
            "type": "wat"
        }
    }
}
```

There's one slightly off topic thing I'd like to add, I think that most if not all example types can technically be consolidated into the tabbed example type, it can already do HTML, CSS, and JS, it is already almost identical to the tabbed-webapi example type, by just adding a console to it and a few more configuration options it can probably handle most (all?) of the existing examples.
Of course, such a change would be a big rewrite of the codebase, and is certainly outside of the scope of this issue, but I figured it might be worth mentioning, after spending a fair amount of time in this repo.

### CODE REVIEW

**Comment by schalkneethling** [comment]
Hey @MendyBerger, thank you so much for this. I will have a look at it as soon as possible. I just might be able to get to this sooner than expected. Will keep you posted.

**Comment by schalkneethling** [comment]
@MendyBerger I am going to bring this up with the product team today and get their feedback on when it would be best to get this into MDN. Thank you for your patience.

**Comment by MendyBerger** [comment]
Thanks! Fingers crossed 🤞

**Comment by MendyBerger** [comment]
@schalkneethling any updates that you can share yet?

**Comment by schalkneethling** [comment]
> @schalkneethling any updates that you can share yet?

Will get back to you today @MendyBerger. Thank you again for your patience. Would you mind pulling down and merging the latest from `main` to resolve the current conflicts?

**Comment by MendyBerger** [comment]
Will do, but it looks like a lot of conflicts, so it might take a few days until I find the time

**Comment by schalkneethling** [comment]
> Will do, but it looks like a lot of conflicts, so it might take a few days until I find the time

Seeing that I am going to review it starting tomorrow. I can also resolve these and push a commit to your branch. Does that work for you?

**Comment by MendyBerger** [comment]
Definitely works, thanks!

**Comment by MendyBerger** [comment]
Looks like you hadn't had the time to resolve those issue so I did it, I believe that there are no conflicts anymore

**Comment by schalkneethling** [comment]
> Looks like you hadn't had the time to resolve those issue so I did it, I believe that there are no conflicts anymore

Thanks so much. I indeed did not get to it on Friday. On my to-do today.

**Comment by schalkneethling** [comment]
Hey @MendyBerger,

I just pulled down the PR, built and started the server but, there are no WASM pages built. Could you add a sample to the repo/pull request? Here: https://github.com/mdn/bob/tree/main/live-examples

Thanks!

**Comment by MendyBerger** [comment]
@schalkneethling added!

**Comment by schalkneethling** [comment]
> @schalkneethling added!

Thank you!

**Comment by schalkneethling** [comment]
@MendyBerger This looks great! I am having a discussion with some other folks on the team and will get back to you tomorrow.

**Comment by schalkneethling** [comment]
@ddbeck Please could you post your guidelines here for how we go forward once this is merged. Thanks!

**Comment by ddbeck** [comment]
OK, once this is merged, here's what needs to happen to make sure that new wasm examples actually make it to MDN:

When you open a PR creating a wasm interactive example, open a corresponding PR adding it to the relevant content page at the same time. Link the two PRs to each other in their respective descriptions. In the description, make a note that both PRs need to merge at around the same time.

Right now, we have a bit of a visibility problem when it comes to reviewing non-mdn/content PRs. This will ensure that likely reviewers will see and review both PRs. Thank you!

**Comment by schalkneethling** [comment]
And with that, let’s merge this. thanks for your work on this @MendyBerger 🎉

**Pull request merged**
