### PR TITLE
ci: Add NPM publish simulation workflow

### PR DESCRIPTION
**Pull request by queengooborg**
Requested by https://github.com/mdn/bob/pull/1109#issuecomment-1438122601.

### CODE REVIEW

**Comment by caugner** [comment]
@queengooborg What confuses me is the fact that the workflow passes, even though it doesn't have the moved dependencies yet?

Should the workflow rather us `npx install-local`?

**Comment by queengooborg** [comment]
Hmm, `install-local` is also passing apparently?

**Comment by queengooborg** [comment]
`install-local` shows more promising results!  Should we do the same for Yari?

**Comment by caugner** [comment]
> `install-local` shows more promising results! Should we do the same for Yari?

Let's wait with that until yari (and content) have moved to npm, which is blocked by the upcoming GCP migration (that'll make the lambdas - and the deployer - redundant).

**Review by caugner — APPROVED** [review]

**Pull request merged**
