### PR TITLE
fix(js-editor): add autorefresh.js addon

### PR DESCRIPTION
**Pull request by peterbe**
This is quite a huge change. But it's definitely in the right direction. 
First of all, the most important change is that we include `autorefresh.js` into the DOM and when we instanciate the `CodeMirror` instance we need to specify to use the `autorefresh` addon. 

The other huge change is that this removes the vendored in `codemirror.js` and `codemirror.css` and other addons that should come from `node_modules` instead.

### CODE REVIEW

**Comment by peterbe** [comment]
There is a LOT else we can do such as stop vendoring in Prism and use node_modules for that too. Separate PR when time allows.

**Comment by peterbe** [comment]
By the way, make sure you look at https://github.com/mdn/kuma/issues/6310#issuecomment-574352330

**Comment by schalkneethling** [comment]
We have not had reports of the tabbed editor behaving in a similar manner, for example here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

But, perhaps it makes sense to set-up `autoRefresh` here as well?

We do call refresh here:
https://github.com/mdn/bob/blob/master/editor/js/editor-libs/tabby.js#L168

So, perhaps adding the property here:
https://github.com/mdn/bob/blob/master/editor/js/editor-libs/tabby.js#L95

would then also remove the need for the call to `refresh` on line 168? With that said, perhaps we can do that in a separate PR so we keep this one all about the JS editor. Let me know your thoughts @peterbe

**Comment by peterbe** [comment]
I'm trying to understand why there are two different ways the `CodeMirror` gets instantiated. Like, in some places it uses a config and some places it uses it more "hard coded". 

Either way, I think the next and right thing to do is to only add the addon in the JS editor. But is that the same as the CSS editor?

**Comment by peterbe** [comment]
@schalkneethling Address that what you mentioned. I also noticed that it loaded `mode/css.js` twice.

**Comment by schalkneethling** [comment]
> I'm trying to understand why there are two different ways the `CodeMirror` gets instantiated. Like, in some places it uses a config and some places it uses it more "hard coded".

Yeah, it evolved and not everything was backported to the what came before:)

**Pull request merged**
