### PR TITLE
refactor!: convert to TypeScript

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
This PR changes all `.js` files in `editor/js` to `.ts` and adds a minimum amount of necessary changes to remove basic errors, so it is easier to be reviewed.

- Changes to `.eslintrc.json` were done because importing other modules was throwing an error. The same thing is done in #1164 
- I changed back code `async function () {}.constructor;` to the version with `Object.getPrototypeOf` because error `This expression is not constructable. Type 'Function' has no construct signatures.` was being thrown.
- I removed `handleChoiceEvent` because the replacement is easier to be understood and we don't need to rely on this.

### CODE REVIEW

**Comment by queengooborg** [comment]
Hey @NiedziolkaMichal!  If you're down to rebase this, I'd be happy to get this merged shortly!

**Review by queengooborg — DISMISSED** [review]

**Comment by caugner** [comment]
@queengooborg There are some conflicts. Would you mind taking a look at those?

PS: I'm not sure, why the tests don't run on this PR. 😕

**Comment by queengooborg** [comment]
> There are some conflicts. Would you mind taking a look at those?

They have been fixed now!

> PS: I'm not sure, why the tests don't run on this PR. 😕

I think that was just a fluke; they're running on the latest commit it looks like.

**Comment by caugner** [comment]
@queengooborg Unfortunately, the tests are not passing yet. I'd be okay with `@ts-ignore`ing all those errors for now, and fix them in a separate PR.

**Comment by queengooborg** [comment]
Alright, so I've finished adding the remaining typedefs to the files and resolving TypeScript errors.  I'm successfully able to run BoB and have had no problems with the interactive examples BoB hosts.  I'm also successfully able to build and test BoB.  However, it appears that building BoB from within `interactive-examples` isn't working, and I don't know why.

**Comment by caugner** [comment]
@queengooborg It looks like 981875dc988fb21d82405751db68b092e149ff8a did the trick, at least for running bob in the context of interactive-examples.

**Comment by caugner** [comment]
As for the failing puppeteer test, I can reproduce this locally on http://127.0.0.1:4444/pages/js/array-concat.html, it looks like the JS editor does not get initialized:

image

The DevTools don't show any console or network errors (apart from `favicon.ico`).

**Comment by queengooborg** [comment]
Hmm, I wasn't able to reproduce the issue locally until now -- I'll see if I can fix it!

**Comment by queengooborg** [comment]
Ah, figured out what it was and was able to fix it!  I also added debugging logging to announce when such a case occurs again.

**Review by caugner — APPROVED** [review]

**Comment by caugner** [comment]
Awesome work, @queengooborg! 🙌

**Comment by queengooborg** [comment]
Thanks to @NiedziolkaMichal as well!  Super excited for this to land!

**Comment by caugner** [comment]
Oh yes, sincere apologies, @NiedziolkaMichal indeed started this initiative, laying the most important groundwork and @queengooborg polished it and brought it over the finish line. Nice collaboration, glad to see this work accomplished! 🎉

**Pull request merged**
