### PR TITLE
fix(deps): Move build dependencies to non-dev dependencies

### PR DESCRIPTION
**Pull request by queengooborg**
This PR moves dependencies required for building from the devDependencies to regular dependencies.

### CODE REVIEW

**Comment by caugner** [comment]
@queengooborg This timeout is weird. Were you able to run the tests locally?

```
> @mdn/bob@3.0.0 jest
> JEST_PUPPETEER_CONFIG=jest-puppeteer.config.cjs NODE_OPTIONS=--experimental-vm-modules jest

Server has taken more than 5000ms to start.


☝️ You can set "server.launchTimeout" in jest-puppeteer.config.js
```

**Comment by queengooborg** [comment]
I was not, and it's actually failing on the `main` branch as well; you can see the fails in all the open Dependabot PRs.  This seems to be caused by some incompatibility with NodeJS v18 (tests pass in 8df94dd1a08125ce83a55233429726500cfc779f using NodeJS v16).

**Comment by caugner** [comment]
@queengooborg Did you check (and how) if those two dependencies are all that need to be moved?

**Comment by queengooborg** [comment]
I checked by running the following:

```sh
cd mdn-interactive-examples
npx install-local ../mdn-bob
npm run build
```

**Comment by caugner** [comment]
> I checked by running the following:

Hm, if I run `npx local-install ../mdn-bob` in `interactive-examples` (with node v18.12.1) I'm getting a 404 error:

```
npx local-install ../bob                                                                                                      1 ↵ ✭
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/local-install - Not found
npm ERR! 404 
npm ERR! 404  'local-install@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Did I miss anything?

**Comment by caugner** [comment]
> Did I miss anything?

It's `npx install-local`.

But I'm still getting an error 😕:

```
% npm run build                                                                                                                     ✭

> interactive-examples@1.0.4 build
> mdn-bob

node:internal/modules/cjs/loader:995
  const err = new Error(message);
              ^

Error: Cannot find module 'path-browserify'
Require stack:
- /Users/claas/github/mdn/interactive-examples/node_modules/@mdn/bob/webpack.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at file:///Users/claas/github/mdn/interactive-examples/node_modules/@mdn/bob/webpack.config.js:72:21
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/claas/github/mdn/interactive-examples/node_modules/@mdn/bob/webpack.config.js'
  ]
}

Node.js v18.12.1
```

**Comment by queengooborg** [comment]
> It's `npx install-local`.

Oops, wrote that reply from my phone and forgot the command for a second... 😆 

> But I'm still getting an error 😕:

That's odd, I wonder why that error didn't pop up on my end...

**Comment by queengooborg** [comment]
Ah, I realize now what I was doing wrong; I was running `npm i` after `npx install-local`.  🤦 

Anyways, I've also updated the test to also perform a clean install before building, and then install the dev dependencies before running the tests with Jest.  It looks like that was the last dependency that shouldn't have been a dev dependency!

**Comment by caugner** [comment]
@queengooborg Thank you. I have got another error now though:

image

Here's what I did:

```sh
cd bob
npm run build
cd ../interactive-examples
npx install-local
npm run build
```

**Comment by queengooborg** [comment]
😠 

It looks like this has something to do with folder resolution with Webpack -- I'll submit another PR to fix that up to keep the scope of this PR down!

**Comment by queengooborg** [comment]
This is now all that's left to get BoB fixed in production!

**Review by caugner — APPROVED** [review]

**Comment by caugner** [comment]
🍿

**Pull request merged**
